sudo: required
services:
  - docker
language: python
python:
- 3.6
os:
- linux
install:
- pip install --upgrade cwltool==3.1.20210816212154
- pip install --upgrade cwltest==2.1.20210626101542
- pip install --upgrade schema-salad==8.2.20210914115719
- pip install --upgrade ruamel.yaml==0.17.10
#script: bash run_test.sh -n171 --verbose --junit-xml=result.xml RUNNER=cwltool
#/home/travis/virtualenv/python3.6.3/bin/cwltool
#script: cd ./tests/ && cwltool --debug --outdir=/tmp/tmpul0j1uu1 ../workflows/genome-indices.cwl ./genome-indices.json
script: bash run_test.sh --junit-xml=result.xml -j2 RUNNER=cwltool
branches:
  only:
  - master
notifications:
  email: false
addons:
  hosts:
    - schema.org
