sudo: required
services:
  - docker
language: python
python:
- 3.6
os:
- linux
install:
- pip install --upgrade cwltool==1.0.20190831161204
- pip install --upgrade cwltest==2.0.20200117101530
- pip install --upgrade schema-salad==4.5.20190815125611
- pip install --upgrade ruamel.yaml==0.15.97
#script: bash run_test.sh -n171 --verbose --junit-xml=result.xml RUNNER=cwltool
#/home/travis/virtualenv/python3.6.3/bin/cwltool
#script: cd ./tests/ && cwltool --debug --outdir=/tmp/tmpul0j1uu1 ../workflows/genome-indices.cwl ./genome-indices.json
script: bash run_test.sh --junit-xml=result.xml RUNNER=cwltool
branches:
  only:
  - master
notifications:
  email: false
addons:
  hosts:
    - schema.org
