name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
    paths:
      - 'tools/dockerfiles/scidap-deseq-Dockerfile'
      - 'tools/dockerfiles/scripts/**'
      - 'tools/dockerfiles/requirements/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'tools/dockerfiles/scidap-deseq-Dockerfile'
      - 'tools/dockerfiles/scripts/**'
      - 'tools/dockerfiles/requirements/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME_DESEQ: biowardrobe2/scidap-deseq

jobs:
  build-deseq:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from Dockerfile
      id: version
      run: |
        VERSION=$(grep "Software Version:" tools/dockerfiles/scidap-deseq-Dockerfile | sed 's/.*v\([0-9]\+\.[0-9]\+\.[0-9]\+\).*//')
        echo "version=v${VERSION}" >> $GITHUB_OUTPUT
        echo "Detected version: v${VERSION}"

    - name: Build and push DESeq Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: tools/dockerfiles/scidap-deseq-Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.IMAGE_NAME_DESEQ }}:${{ steps.version.outputs.version }}
          ${{ env.IMAGE_NAME_DESEQ }}:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Image digest
      if: github.event_name != 'pull_request'
      run: echo "Image pushed with digest ${{ steps.build.outputs.digest }}"
